---
- name: Add custom syslog configuration
  blockinfile:
    path: "{{ syslog_config['conf_location'] }}"
    block: |
      # Custom syslog server
      *.warn;kern.none @{{ syslog_config['server'] }}
    backup: "{{ syslog_config['backup_config'] }}"
    create: yes

- name: Restart and activate Syslog service
  service:
    name: "{{ syslog_config['service_name'] }}"
    state: restarted
    enabled: yes