---
- name: Remove already existing SMTP config to avoid conflict
  lineinfile:
    path: "{{ smtp_config['conf_location'] }}"
    state: absent
    regexp: "^(# BEGIN ANSIBLE MANAGED BLOCK|set smtp=|set hostname=|# END ANSIBLE MANAGED BLOCK)"
    backup: "{{ smtp_config['backup_config'] }}"
    create: yes

- name: Add SMTP configuration
  blockinfile:
    path: "{{ smtp_config['conf_location'] }}"
    block: |
      set smtp="{{ smtp_config['host'] }}"
      set hostname="{{ ansible_nodename }}"
    backup: "{{ smtp_config['backup_config'] }}"
    create: yes

- name: Send a test email
  mail:
    host: "{{ smtp_config['host'] }}"
    port: "{{ smtp_config['port'] }}"
    subject: "[Ansible Bootstrap] Test e-mail from {{ inventory_hostname }}"
    body: "This a test email !"
    from: "{{ smtp_config['test_from'] }}"
    to: "{{ smtp_config['test_to'] }}"
  when: smtp_config['test']
  ignore_errors: yes