---
- name: Reboot machine and send a message
  reboot:
    msg: "Rebooting machine in 5 seconds"

- name: Wait for VM rebooting
  wait_for:
    host: "{{ host_config['network']['ip'] }}"
    port: 22
    delay: 60
    state: present

- name: Display end message
  debug:
    msg: Machine bootstrapped with success !