---
- name: Reboot machine and send a message
  reboot:
    msg: "Rebooting machine in 5 seconds"

- name: Wait for VM rebooting
  wait_for:
    host: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    port: 22
    delay: 60
    state: present
  delegate_to: localhost

- name: Display end message
  debug:
    msg: Machine bootstrapped with success !
  delegate_to: localhost